server:
  port: 8084 # 避免端口冲突

spring:
  application:
    name: ai-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
      config:
        server-addr: 127.0.0.1
        username: nacos
        password: nacos
        file-extension: yaml
        group: whyh
        shared-configs:
          - data-id: oss-service-${spring.profiles.active}.yaml
            group: whyh
            refresh: true