server:
  port: 8086

spring:
  application:
    name: content-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user_center?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1729328500
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000

